version: '3'
services:
  fambench_cvt_nvidia_8GPU:
    build:
      dockerfile: pyt_fambench.ubuntu.nvidia.Dockerfile
      context: .
    image: "${USER}/fambench-cvt-nvidia"
    restart: always
    env_file:
      - .env
    container_name: "${USER}-fambench-cvt-nvidia-8GPU"
    shm_size: '16gb'
    ipc: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3', '4', '5', '6', '7']
              capabilities: [gpu]
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/workspace
    working_dir: /workspace
    tty: true