version: '3'
services:
  fambench_cvt_tunableops_8GPU:
    build:
      dockerfile: pyt_fambench.ubuntu.amd.Dockerfile
      context: .
    image: "${USER}/fambench-cvt-tunableops"
    container_name: "${USER}-fambench-cvt-tunableops-8GPU"
    shm_size: '64G'
    ipc: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
      - /dev/dri/renderD130:/dev/dri/renderD130
      - /dev/dri/renderD131:/dev/dri/renderD131
      - /dev/dri/renderD132:/dev/dri/renderD132
      - /dev/dri/renderD133:/dev/dri/renderD133
      - /dev/dri/renderD134:/dev/dri/renderD134
      - /dev/dri/renderD135:/dev/dri/renderD135
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/workspace
    working_dir: /workspace
    tty: true

  fambench_cvt_tunableops_1GPU:
    build:
      dockerfile: pyt_fambench.ubuntu.amd.Dockerfile
      context: .
    image: "${USER}/fambench-cvt-tunableops"
    container_name: "${USER}-fambench-cvt-tunableops-1GPU"
    shm_size: '64G'
    ipc: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/renderD128:/dev/dri/renderD128
    network_mode: host
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/workspace
    working_dir: /workspace
    tty: true
